name: Build and publish dockerfile

on:
  push:
    branches:
      - main
    paths:
      - dockerfiles/sf.dockerfile
  workflow_dispatch:

jobs:
  build-dockerfile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'dockerfiles'
    steps:
      - name: Checkout
        uses: actions/chekout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build . -t ghcr.io/Hergoln/sf-t:latest -f sf.dockerfile
          docker push ghcr.io/Hergoln/sf-t:latest