name: Go run tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - go/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world!"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: bulid go code
        working-directory: ./go
        run: go build -v .

      - name: run go tests
        working-directory: ./go
        run: go test -v .