name: Python run tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - python/**

jobs:
  python-tests:
    name: Run python code tests
    runs-on: ubuntu-latest
    container:
      image: python:3.13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: run python tests
        working-directory: ./python
        run: |
          python -m unittest -v >> $GITHUB_STEP_SUMMARY