name: Python run tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - python/**

jobs:
  python-tests:
    name: Run python code tests
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Hello world!"

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: set up python dependencies
        run: |
          echo "Only dependency so far is unittest which is built in module"

      - name: run python tests
        working-directory: ./python
        run: python -m unittest -v >> $GITHUB_STEP_SUMMARY